[package]
name = "lemmy_apub_lib_derive"
version = "0.11.3"
edition = "2018"
description = "A link aggregator for the fediverse"
license = "AGPL-3.0"

[lib]
proc-macro = true

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
quote = "1.0"
